package com.example.ui.util

import com.example.data.repository.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        val map = when (language) {
            AppLanguage.PASHTO -> pashtoMap
            AppLanguage.DARI -> dariMap
            AppLanguage.ENGLISH -> englishMap
        }
        return map[key] ?: englishMap[key] ?: key
    }

    private val englishMap = mapOf(
        "app_title" to "My Daily",
        "home" to "Home",
        "tasks" to "Tasks",
        "money" to "Money",
        "notes" to "Notes",
        "more" to "More",
        "shopping" to "Shopping",
        "reminders" to "Reminders",
        "settings" to "Settings",
        "good_morning" to "Good Morning",
        "good_afternoon" to "Good Afternoon",
        "good_evening" to "Good Evening",
        "todays_quote" to "Daily Inspiration",
        "today_tasks" to "Today's Tasks",
        "pending" to "Pending",
        "completed" to "Completed",
        "no_tasks" to "No tasks scheduled for today. Tap + to add one!",
        "view_all" to "View All",
        "financial_snapshot" to "Financial Overview",
        "income" to "Income",
        "expense" to "Expense",
        "balance" to "Remaining Balance",
        "today_spending" to "Today's Spending",
        "week_spending" to "This Week",
        "month_spending" to "This Month",
        "quick_notes" to "Quick Notes",
        "no_notes" to "No notes yet. Tap + to capture your thoughts.",
        "upcoming_reminders" to "Upcoming Reminders",
        "add_task" to "Add Task",
        "task_title" to "Task title",
        "task_desc" to "Notes / details (optional)",
        "priority" to "Priority",
        "category" to "Category",
        "due_date" to "Due Date",
        "low" to "Low",
        "medium" to "Medium",
        "high" to "High",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "add_transaction" to "Add Transaction",
        "amount" to "Amount",
        "description" to "Description (optional)",
        "add_note" to "New Note",
        "note_title" to "Title",
        "note_body" to "Write your note here...",
        "pin_note" to "Pin note",
        "add_shopping_item" to "Add Shopping Item",
        "item_name" to "Item name (e.g. Milk, Rice, Sugar)",
        "quantity" to "Quantity (e.g. 2 kg, 1 pack)",
        "list_name" to "Category / List",
        "clear_purchased" to "Clear Done",
        "add_reminder" to "New Reminder",
        "time" to "Time",
        "repeat" to "Repeat",
        "app_lock" to "App Lock",
        "enter_pin" to "Enter 4-digit PIN",
        "setup_pin" to "Set New PIN",
        "wrong_pin" to "Incorrect PIN. Please try again.",
        "theme" to "Theme",
        "currency" to "Currency",
        "language" to "Language",
        "backup_restore" to "Backup & Restore",
        "export_backup" to "Export Data (JSON)",
        "import_backup" to "Import Data (JSON)",
        "backup_exported" to "Backup JSON copied / ready!",
        "backup_imported" to "Backup successfully restored!",
        "backup_error" to "Invalid backup format.",
        "search_hint" to "Search anything...",
        "privacy_note" to "Private & Offline-First. Your data never leaves your device."
    )

    private val pashtoMap = mapOf(
        "app_title" to "زما ورځنی",
        "home" to "کور",
        "tasks" to "دندې",
        "money" to "پیسې",
        "notes" to "یادښتونه",
        "more" to "نور",
        "shopping" to "خریداری",
        "reminders" to "یادونې",
        "settings" to "تنظیمات",
        "good_morning" to "سهار په خیر",
        "good_afternoon" to "ماسپښین په خیر",
        "good_evening" to "ماښام په خیر",
        "todays_quote" to "د ورځې الهام",
        "today_tasks" to "د نن ورځې دندې",
        "pending" to "پاتې",
        "completed" to "بشپړې شوې",
        "no_tasks" to "نن کومه دنده نشته. نوی کار اضافه کړئ!",
        "view_all" to "ټول وګورئ",
        "financial_snapshot" to "مالي کتنه",
        "income" to "عاید",
        "expense" to "مصرف",
        "balance" to "پاتې شونی",
        "today_spending" to "د نن مصرف",
        "week_spending" to "د دې اونۍ مصرف",
        "month_spending" to "د دې میاشتې مصرف",
        "quick_notes" to "چټک یادښتونه",
        "no_notes" to "تر اوسه یادښت نشته.",
        "upcoming_reminders" to "راتلونکې یادونې",
        "add_task" to "نوې دنده",
        "task_title" to "د دندې سرلیک",
        "task_desc" to "توضیحات (اختیاري)",
        "priority" to "لومړیتوب",
        "category" to "کټګوري",
        "due_date" to "د پای نیټه",
        "low" to "ټیټ",
        "medium" to "منځنی",
        "high" to "لوړ",
        "save" to "ساتل",
        "cancel" to "لغوه",
        "delete" to "حذف",
        "edit" to "سمول",
        "add_transaction" to "نوې راکړه ورکړه",
        "amount" to "اندازه",
        "description" to "تفصیل",
        "add_note" to "نوی یادښت",
        "note_title" to "سرلیک",
        "note_body" to "دلته خپل یادښت ولیکئ...",
        "pin_note" to "پین کول",
        "add_shopping_item" to "د سودا توکی",
        "item_name" to "د توکي نوم (لکه بوره، وریجې)",
        "quantity" to "شمېر / وزن",
        "list_name" to "د لیست نوم",
        "clear_purchased" to "پیرودل شوي پاکول",
        "add_reminder" to "نوې یادونه",
        "time" to "وخت",
        "repeat" to "تکرار",
        "app_lock" to "د اپلیکیشن قلف",
        "enter_pin" to "۴-عددي پین کوډ ولیکئ",
        "setup_pin" to "نوی پین وټاکئ",
        "wrong_pin" to "پین ناسم دی. بیا هڅه وکړئ.",
        "theme" to "رنګ بڼه",
        "currency" to "پولي واحد",
        "language" to "ژبه",
        "backup_restore" to "بیک اپ او بحالول",
        "export_backup" to "ډیټا استخراج (JSON)",
        "import_backup" to "ډیټا بیا راګرځول (JSON)",
        "backup_exported" to "بیک اپ کاپي شو!",
        "backup_imported" to "ډیټا په بریا راوګرځول شوه!",
        "backup_error" to "ناسم فارمټ.",
        "search_hint" to "لټون وکړئ...",
        "privacy_note" to "شخصي او آفلاین. ستاسو معلومات تل ستاسو په وسیله کې خوندي پاتې کیږي."
    )

    private val dariMap = mapOf(
        "app_title" to "روزانه‌های من",
        "home" to "خانه",
        "tasks" to "وظایف",
        "money" to "مالی",
        "notes" to "یادداشت‌ها",
        "more" to "بیشتر",
        "shopping" to "خریداری",
        "reminders" to "یادآوری‌ها",
        "settings" to "تنظیمات",
        "good_morning" to "صبح بخیر",
        "good_afternoon" to "بعد از ظهر بخیر",
        "good_evening" to "عصر بخیر",
        "todays_quote" to "انگیزه روزانه",
        "today_tasks" to "وظایف امروز",
        "pending" to "در انتظار",
        "completed" to "تکمیل شده",
        "no_tasks" to "امروز کاری ثبت نشده است. با دکمه + اضافه کنید!",
        "view_all" to "مشاهده همه",
        "financial_snapshot" to "مرور وضعیت مالی",
        "income" to "درآمد",
        "expense" to "مصرف",
        "balance" to "موجودی باقیمانده",
        "today_spending" to "مصرف امروز",
        "week_spending" to "مصرف این هفته",
        "month_spending" to "مصرف این ماه",
        "quick_notes" to "یادداشت‌های سریع",
        "no_notes" to "هنوز یادداشتی ثبت نشده است.",
        "upcoming_reminders" to "یادآوری‌های پیش رو",
        "add_task" to "وظیفه جدید",
        "task_title" to "عنوان وظیفه",
        "task_desc" to "توضیحات (اختیاری)",
        "priority" to "اولویت",
        "category" to "دسته‌بندی",
        "due_date" to "تاریخ موعد",
        "low" to "پایین",
        "medium" to "متوسط",
        "high" to "بالا",
        "save" to "ذخیره",
        "cancel" to "انصراف",
        "delete" to "حذف",
        "edit" to "ویرایش",
        "add_transaction" to "ثبت دخل و خرج",
        "amount" to "مبلغ",
        "description" to "توضیحات",
        "add_note" to "یادداشت جدید",
        "note_title" to "عنوان",
        "note_body" to "یادداشت خود را اینجا بنویسید...",
        "pin_note" to "سنجاق کردن",
        "add_shopping_item" to "مورد خرید",
        "item_name" to "نام جنس (مثلا برنج، روغن)",
        "quantity" to "تعداد / مقدار",
        "list_name" to "نام لیست",
        "clear_purchased" to "پاک کردن خریداری شده‌ها",
        "add_reminder" to "یادآوری جدید",
        "time" to "زمان",
        "repeat" to "تکرار",
        "app_lock" to "قفل برنامه",
        "enter_pin" to "رمز ۴ رقمی را وارد کنید",
        "setup_pin" to "تنظیم رمز جدید",
        "wrong_pin" to "رمز اشتباه است. دوباره امتحان کنید.",
        "theme" to "حالت تم",
        "currency" to "واحد پول",
        "language" to "زبان",
        "backup_restore" to "پشتیبان‌گیری و بازیابی",
        "export_backup" to "خروجی اطلاعات (JSON)",
        "import_backup" to "بازیابی اطلاعات (JSON)",
        "backup_exported" to "فایل پشتیبان آماده شد!",
        "backup_imported" to "اطلاعات با موفقیت بازیابی شد!",
        "backup_error" to "قالب نامعتبر است.",
        "search_hint" to "جستجو...",
        "privacy_note" to "خصوصی و کاملاً آفلاین. اطلاعات شخصی شما هرگز از دستگاه خارج نمی‌شود."
    )
}
